### ISSUE TITLE
Investigate possible race condition in building igvc_msgs

### ISSUE THREAD

**Issue by rmkeezer** [RoboJackets/igvc-software#149]
CircleCI is sometimes not building igvc_msgs before igvc. This should have been fixed a while ago. If anyone is failing builds on master please post the log here

**Comment by dpattison3** [comment]
Rviz plugings are the only module that doesn't set messages as a dependency (it wasn't compiling when I fixed the earlier issue anyway). Should it depend on messages? That's the only recent thing to change right?

**Comment by JasonGibson274** [comment]
I think we should close this issue and reopen it if the issue returns. CircleCI seems to be building fine to me.

**Comment by jgkamat** [comment]
This is still happening, just at a much reduced rate. [See this build log for details](https://271-16996386-gh.circle-artifacts.com/0/tmp/circle-artifacts.rnZw4Il/compile.txt). I /think/ that rviz_plugins needs to depend on igvc_msgs as well (although, since igvc depends on it, shouldn't igvc_msgs depend on it as well?).
